Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1256, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/util.py", line 87, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 694, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1012, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 906, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Gk=reduced_Cartesian_power(graphs.CycleGraph(4),2,edge_labels='cannonical')
Gk.show(figsize=8,edge_labels=true)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [7], line 1[0m
[0;32m----> 1[0m Gk[38;5;241m=[39m[43mreduced_Cartesian_power[49m(graphs[38;5;241m.[39mCycleGraph(Integer([38;5;241m4[39m)),Integer([38;5;241m2[39m),edge_labels[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcannonical[39m[38;5;124m'[39m)
[1;32m      2[0m Gk[38;5;241m.[39mshow(figsize[38;5;241m=[39mInteger([38;5;241m8[39m),edge_labels[38;5;241m=[39mtrue)

[0;31mNameError[0m: name 'reduced_Cartesian_power' is not defined
NameError: name 'reduced_Cartesian_power' is not defined

